-- MySQL Script generated by MySQL Workbench
-- Wed Apr 25 09:52:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qudiancan
-- -----------------------------------------------------
-- 去点餐
DROP SCHEMA IF EXISTS `qudiancan` ;

-- -----------------------------------------------------
-- Schema qudiancan
--
-- 去点餐
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qudiancan` DEFAULT CHARACTER SET utf8 ;
USE `qudiancan` ;

-- -----------------------------------------------------
-- Table `qudiancan`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`shop` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`shop` (
  `id` VARCHAR(16) NOT NULL COMMENT '主键',
  `name` VARCHAR(16) NULL COMMENT '餐厅或品牌名称',
  `holder_type` VARCHAR(16) NULL COMMENT '主体类型',
  `holder_name` VARCHAR(16) NULL COMMENT '个人名称或企业名称',
  `holder_identify` VARCHAR(18) NULL COMMENT '个人身份证或企业统一社会信用代码',
  `telephone` VARCHAR(16) NULL COMMENT '电话或手机',
  `introduction` VARCHAR(255) NULL COMMENT '介绍',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '餐厅';


-- -----------------------------------------------------
-- Table `qudiancan`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`account` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` VARCHAR(16) NOT NULL COMMENT '餐厅id',
  `login_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '登录id',
  `password` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '密码',
  `name` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '姓名',
  `email` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '电子邮箱',
  `phone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '手机',
  `branch_ids` VARCHAR(255) NULL COMMENT '所属门店',
  `role_ids` VARCHAR(255) NULL COMMENT '所属角色',
  `is_creator` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '是否为餐厅创建者',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shop_account_shop_subject`
    FOREIGN KEY (`shop_id`)
    REFERENCES `qudiancan`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '账号';


-- -----------------------------------------------------
-- Table `qudiancan`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`role` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `description` VARCHAR(64) NULL COMMENT '描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` VARCHAR(16) NOT NULL COMMENT '餐厅id',
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `notice` VARCHAR(255) NULL COMMENT '公告',
  `phone` VARCHAR(16) NOT NULL COMMENT '手机号',
  `address` VARCHAR(255) NOT NULL COMMENT '地址',
  `longitude` VARCHAR(16) NOT NULL COMMENT '经度',
  `latitude` VARCHAR(16) NOT NULL COMMENT '纬度',
  `introduction` VARCHAR(255) NULL COMMENT '介绍',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shop_branch_shop_subject1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `qudiancan`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店';


-- -----------------------------------------------------
-- Table `qudiancan`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`product_category` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`product_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '门店id',
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `position` INT UNSIGNED NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_product_category_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '产品类目';


-- -----------------------------------------------------
-- Table `qudiancan`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`department` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`department` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '门店id',
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `description` VARCHAR(255) NOT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_department_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '出品部门';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch_product` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '门店id',
  `category_id` INT UNSIGNED NOT NULL COMMENT '产品类目id',
  `department_id` INT UNSIGNED NOT NULL COMMENT '出品部门id',
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `image` VARCHAR(255) NULL COMMENT '图片',
  `unit_name` VARCHAR(16) NOT NULL COMMENT '单位',
  `price` DECIMAL(8,2) NOT NULL COMMENT '单价',
  `description` VARCHAR(255) NULL COMMENT '描述',
  `position` INT UNSIGNED NOT NULL COMMENT '产品类目内排序',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_product_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_product_branch_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `qudiancan`.`product_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_product_branch_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `qudiancan`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店产品';


-- -----------------------------------------------------
-- Table `qudiancan`.`table_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`table_category` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`table_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '门店id',
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `position` INT UNSIGNED NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_table_category_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '桌台类目';


-- -----------------------------------------------------
-- Table `qudiancan`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`member` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`member` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` VARCHAR(16) NOT NULL COMMENT '餐厅id',
  `openid` VARCHAR(255) NULL COMMENT '微信用户openid',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shop_member_shop_subject1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `qudiancan`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '会员';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch_order` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '门店id',
  `branch_name` VARCHAR(16) NOT NULL COMMENT '门店名称',
  `table_id` INT UNSIGNED NULL COMMENT '桌台id',
  `member_id` INT UNSIGNED NULL COMMENT '会员id',
  `order_number` VARCHAR(32) NOT NULL COMMENT '订单编号',
  `total_sum` DECIMAL(8,2) NOT NULL COMMENT '订单金额',
  `discount_sum` DECIMAL(8,2) NULL COMMENT '折扣金额',
  `wipe_sum` DECIMAL(4,2) NULL COMMENT '抹零金额',
  `charge_sum` DECIMAL(8,2) NULL COMMENT '实收金额',
  `table_name` VARCHAR(16) NULL COMMENT '桌台名称',
  `note` VARCHAR(255) NULL COMMENT '订单备注',
  `pay_method` VARCHAR(16) NULL COMMENT '支付方式',
  `pay_status` VARCHAR(16) NOT NULL COMMENT '支付状态',
  `order_status` VARCHAR(16) NOT NULL COMMENT '订单状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `customer_num` INT NOT NULL COMMENT '客人数',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_order_subject_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_order_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `qudiancan`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_order_branch_table1`
    FOREIGN KEY (`table_id`)
    REFERENCES `qudiancan`.`branch_table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店订单';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch_table` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch_table` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '门店id',
  `category_id` INT UNSIGNED NOT NULL COMMENT '类目id',
  `order_id` INT UNSIGNED NULL COMMENT '占用该桌台的订单id',
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `capacity` INT UNSIGNED NOT NULL COMMENT '可供就餐人数',
  `position` INT UNSIGNED NOT NULL COMMENT '桌台类目内排序',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  `qrcode` VARCHAR(255) NULL COMMENT '小程序二维码地址',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_table_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_table_branch_table_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `qudiancan`.`table_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_table_branch_order_subject1`
    FOREIGN KEY (`order_id`)
    REFERENCES `qudiancan`.`branch_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店桌台';


-- -----------------------------------------------------
-- Table `qudiancan`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`cart` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`cart` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '门店id',
  `member_id` INT NOT NULL COMMENT '微信用户会员id',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_wechat_cart_subject_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '购物车';


-- -----------------------------------------------------
-- Table `qudiancan`.`cart_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`cart_product` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`cart_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `cart_id` INT UNSIGNED NOT NULL COMMENT '购物车id',
  `product_id` INT UNSIGNED NOT NULL COMMENT '产品id',
  `product_num` INT NOT NULL COMMENT '产品数量',
  `product_name` VARCHAR(16) NOT NULL COMMENT '产品名称',
  `product_price` DECIMAL(8,2) NOT NULL COMMENT '产品单价',
  `sum` DECIMAL(8,2) NOT NULL COMMENT '小计',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_wechat_cart_product_wechat_cart_subject1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `qudiancan`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product_branch_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `qudiancan`.`branch_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '购物车产品';


-- -----------------------------------------------------
-- Table `qudiancan`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`order_product` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`order_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` INT UNSIGNED NOT NULL COMMENT '订单id',
  `product_id` INT UNSIGNED NOT NULL COMMENT '产品id',
  `name` VARCHAR(16) NOT NULL COMMENT '产品名称',
  `price` DECIMAL(8,2) NOT NULL COMMENT '产品价格',
  `num` INT UNSIGNED NOT NULL COMMENT '产品数量',
  `total_sum` DECIMAL(8,2) NOT NULL COMMENT '小计',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_order_product_branch_order_subject1`
    FOREIGN KEY (`order_id`)
    REFERENCES `qudiancan`.`branch_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product_branch_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `qudiancan`.`branch_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '订单产品';


-- -----------------------------------------------------
-- Table `qudiancan`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`authority` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`authority` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `path` VARCHAR(64) NOT NULL COMMENT '访问路径',
  `name` VARCHAR(16) NULL COMMENT '名称',
  `role_ids` VARCHAR(255) NULL COMMENT '所属角色',
  `description` VARCHAR(64) NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `authoritycol_UNIQUE` (`path` ASC))
ENGINE = InnoDB
COMMENT = '权限';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
