-- MySQL Script generated by MySQL Workbench
-- Sun Apr 22 12:17:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qudiancan
-- -----------------------------------------------------
-- 去点餐
DROP SCHEMA IF EXISTS `qudiancan` ;

-- -----------------------------------------------------
-- Schema qudiancan
--
-- 去点餐
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qudiancan` DEFAULT CHARACTER SET utf8 ;
USE `qudiancan` ;

-- -----------------------------------------------------
-- Table `qudiancan`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`shop` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`shop` (
  `id` VARCHAR(16) NOT NULL COMMENT '主键',
  `name` VARCHAR(16) NULL COMMENT '平台或品牌名称',
  `holder_type` VARCHAR(16) NULL COMMENT '主体类型',
  `holder_name` VARCHAR(16) NULL COMMENT '个人名称或企业名称',
  `holder_identify` VARCHAR(18) NULL COMMENT '个人身份证或企业统一社会信用代码',
  `telephone` VARCHAR(16) NULL COMMENT '电话或手机',
  `introduction` VARCHAR(255) NULL COMMENT '简介',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '店铺';


-- -----------------------------------------------------
-- Table `qudiancan`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`account` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` VARCHAR(16) NOT NULL,
  `login_id` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '登录id',
  `password` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '密码',
  `name` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '姓名',
  `email` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '电子邮箱',
  `phone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '手机',
  `branch_ids` VARCHAR(255) NULL,
  `role_ids` VARCHAR(255) NULL,
  `is_creator` VARCHAR(16) NOT NULL DEFAULT '',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shop_account_shop_subject`
    FOREIGN KEY (`shop_id`)
    REFERENCES `qudiancan`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '账号';


-- -----------------------------------------------------
-- Table `qudiancan`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`role` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(16) NOT NULL,
  `description` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '店铺角色';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` VARCHAR(16) NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `notice` VARCHAR(255) NULL COMMENT '公告',
  `phone` VARCHAR(16) NOT NULL,
  `address` VARCHAR(255) NOT NULL COMMENT '地址',
  `longitude` VARCHAR(16) NOT NULL COMMENT '经度',
  `latitude` VARCHAR(16) NOT NULL COMMENT '纬度',
  `introduction` VARCHAR(255) NULL COMMENT '介绍',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shop_branch_shop_subject1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `qudiancan`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店';


-- -----------------------------------------------------
-- Table `qudiancan`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`product_category` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`product_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `branch_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `position` INT UNSIGNED NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_product_category_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店产品类目';


-- -----------------------------------------------------
-- Table `qudiancan`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`department` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`department` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `description` VARCHAR(255) NOT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_department_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店出品部门';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch_product` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `department_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `image` VARCHAR(255) NULL COMMENT '图片',
  `unit_name` VARCHAR(16) NOT NULL COMMENT '单位',
  `price` DECIMAL(8,2) NOT NULL COMMENT '单价',
  `description` VARCHAR(255) NULL COMMENT '描述',
  `position` INT UNSIGNED NOT NULL COMMENT '排序',
  `status` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_product_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_product_branch_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `qudiancan`.`product_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_product_branch_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `qudiancan`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店产品';


-- -----------------------------------------------------
-- Table `qudiancan`.`table_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`table_category` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`table_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `position` INT UNSIGNED NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_table_category_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店桌台类目';


-- -----------------------------------------------------
-- Table `qudiancan`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`member` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`member` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` VARCHAR(16) NOT NULL,
  `openid` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shop_member_shop_subject1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `qudiancan`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '店铺会员';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch_order` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL,
  `branch_name` VARCHAR(16) NOT NULL,
  `table_id` INT UNSIGNED NULL,
  `member_id` INT UNSIGNED NULL,
  `order_number` VARCHAR(32) NOT NULL COMMENT '订单编号',
  `total_sum` DECIMAL(8,2) NOT NULL,
  `discount_sum` DECIMAL(8,2) NULL,
  `wipe_sum` DECIMAL(4,2) NULL,
  `charge_sum` DECIMAL(8,2) NULL,
  `table_name` VARCHAR(16) NULL,
  `note` VARCHAR(255) NULL,
  `pay_method` VARCHAR(16) NULL,
  `pay_status` VARCHAR(16) NOT NULL,
  `order_status` VARCHAR(16) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_num` INT NOT NULL COMMENT '客人数',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_order_subject_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_order_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `qudiancan`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_order_branch_table1`
    FOREIGN KEY (`table_id`)
    REFERENCES `qudiancan`.`branch_table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店订单';


-- -----------------------------------------------------
-- Table `qudiancan`.`branch_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`branch_table` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`branch_table` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '名称',
  `capacity` INT UNSIGNED NOT NULL COMMENT '可供就餐人数',
  `position` INT UNSIGNED NOT NULL COMMENT '排序',
  `status` VARCHAR(16) NOT NULL COMMENT '状态',
  `qrcode` VARCHAR(255) NULL COMMENT '小程序二维码地址',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_table_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_table_branch_table_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `qudiancan`.`table_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_table_branch_order_subject1`
    FOREIGN KEY (`order_id`)
    REFERENCES `qudiancan`.`branch_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '门店桌台';


-- -----------------------------------------------------
-- Table `qudiancan`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`cart` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`cart` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `branch_id` INT UNSIGNED NOT NULL,
  `member_id` INT NOT NULL COMMENT '微信用户id',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_wechat_cart_subject_shop_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `qudiancan`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '购物车';


-- -----------------------------------------------------
-- Table `qudiancan`.`cart_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`cart_product` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`cart_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `cart_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `product_num` INT NOT NULL COMMENT '产品数量',
  `product_name` VARCHAR(16) NOT NULL,
  `product_price` DECIMAL(8,2) NOT NULL COMMENT '单价',
  `sum` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_wechat_cart_product_wechat_cart_subject1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `qudiancan`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product_branch_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `qudiancan`.`branch_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '购物车产品';


-- -----------------------------------------------------
-- Table `qudiancan`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`order_product` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`order_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `num` INT UNSIGNED NOT NULL,
  `total_sum` DECIMAL(8,2) NOT NULL,
  `status` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_order_product_branch_order_subject1`
    FOREIGN KEY (`order_id`)
    REFERENCES `qudiancan`.`branch_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product_branch_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `qudiancan`.`branch_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '店铺门店订单产品';


-- -----------------------------------------------------
-- Table `qudiancan`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qudiancan`.`authority` ;

CREATE TABLE IF NOT EXISTS `qudiancan`.`authority` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(64) NOT NULL,
  `name` VARCHAR(16) NULL,
  `role_ids` VARCHAR(255) NULL,
  `description` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `authoritycol_UNIQUE` (`path` ASC))
ENGINE = InnoDB
COMMENT = '权限';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- 初始化角色表
Insert INTO role VALUES(1,"管理员", "店铺管理员");
Insert INTO role VALUES(2,"店长", "门店店长");
Insert INTO role VALUES(3,"主管", "门店主管");
Insert INTO role VALUES(4,"收银员", "门店收银员");
Insert INTO role VALUES(5,"服务员", "门店服务员");

-- 初始化权限表
INSERT INTO authority VALUES(1,"SHOP_SHOP_SHOW","查看店铺","1,2,3,4,5","查看店铺信息");
INSERT INTO authority VALUES(2,"SHOP_SHOP_UPDATE","更新店铺","1,2","更新店铺信息");
INSERT INTO authority VALUES(3,"SHOP_BRANCH_SHOW","查看门店","1,2,3,4,5","查看门店信息");
INSERT INTO authority VALUES(4,"SHOP_BRANCH_CREATE","创建门店","1,2","创建新的门店");
INSERT INTO authority VALUES(5,"SHOP_BRANCH_UPDATE","更新门店","1,2","更新门店信息");
INSERT INTO authority VALUES(6,"BRANCH_CATEGORY_SHOW","查看产品类目","1,2,3,4,5","查看产品类目信息");
INSERT INTO authority VALUES(7,"BRANCH_CATEGORY_CREATE","创建产品类目","1,2,3","创建新的产品类目");
INSERT INTO authority VALUES(8,"BRANCH_PRODUCT_CREATE","创建产品","1,2,3","创建新的产品");
INSERT INTO authority VALUES(9,"BRANCH_PRODUCT_SHOW","查看产品","1,2,3,4,5","查看门店产品");
INSERT INTO authority VALUES(10,"BRANCH_PRODUCT_UPDATE","更新产品","1,2,3","更新门店产品");
INSERT INTO authority VALUES(11,"BRANCH_DEPARTMENT_CREATE","创建出品部门","1,2,3","创建新的出品部门");
INSERT INTO authority VALUES(12,"BRANCH_DEPARTMENT_SHOW","查看出品部门","1,2,3,4,5","查看出品部门信息");
INSERT INTO authority VALUES(13,"BRANCH_DEPARTMENT_UPDATE","更新出品部门","1,2,3","更新出品部门信息");
INSERT INTO authority VALUES(14,"BRANCH_TABLE_CATEGORY_CREATE","创建桌台类型","1,2,3","创建桌台类型");
INSERT INTO authority VALUES(15,"BRANCH_TABLE_CATEGORY_SHOW","查看桌台类型","1,2,3,4,5","查看桌台类型");
INSERT INTO authority VALUES(16,"BRANCH_TABLE_CATEGORY_UPDATE","更新桌台类型","1,2,3","更新桌台类型");
INSERT INTO authority VALUES(17,"BRANCH_TABLE_CREATE","创建桌台","1,2,3,4","创建新的桌台");
INSERT INTO authority VALUES(18,"BRANCH_TABLE_SHOW","获取桌台","1,2,3,4,5","获取桌台信息");
INSERT INTO authority VALUES(19,"BRANCH_TABLE_UPDATE","更新桌台","1,2,3,4","更新桌台信息");
INSERT INTO authority VALUES(20,"BRANCH_PRODUCT_UP","上架产品","1,2,3","上架门店产品");
INSERT INTO authority VALUES(21,"BRANCH_PRODUCT_DOWN","下架产品","1,2,3","下架门店产品");
INSERT INTO authority VALUES(22,"SHOP_ACCOUNT_SETTING","账号设置","1,2","账号设置");
INSERT INTO authority VALUES(23,"SHOP_ACCOUNT_CREATE","账号创建","1,2","账号创建");
INSERT INTO authority VALUES(24,"SHOP_BRANCH_CASHIER","收银中心","1,2,3,4,5","收银中心");
INSERT INTO authority VALUES(25,"BRANCH_ORDER_SHOW","查看订单","1,2,3,4","查看订单");
INSERT INTO authority VALUES(26,"BRANCH_ORDER_CREATE","创建订单","1,2,3,4","创建订单");
